# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeserver',
            fields=[
                ('code', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
                ('key', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('usr', models.CharField(max_length=20)),
            ],
        ),
    ]
