# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindrow(object):
    def setupUi(self, mainWindrow):
        mainWindrow.setObjectName("mainWindrow")
        mainWindrow.resize(800, 601)
        mainWindrow.setMinimumSize(QtCore.QSize(800, 601))
        mainWindrow.setMaximumSize(QtCore.QSize(800, 601))
        mainWindrow.setMouseTracking(False)
        mainWindrow.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget = QtWidgets.QWidget(mainWindrow)
        self.widget.setGeometry(QtCore.QRect(20, 20, 761, 371))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.outputEdit = QtWidgets.QTextEdit(self.widget)
        self.outputEdit.setMouseTracking(False)
        self.outputEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.outputEdit.setReadOnly(True)
        self.outputEdit.setObjectName("outputEdit")
        self.gridLayout.addWidget(self.outputEdit, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.portBox = QtWidgets.QComboBox(self.widget)
        self.portBox.setObjectName("portBox")
        self.portBox.addItem("")
        self.portBox.addItem("")
        self.portBox.addItem("")
        self.portBox.addItem("")
        self.portBox.addItem("")
        self.portBox.addItem("")
        self.verticalLayout_2.addWidget(self.portBox)
        self.rateBox = QtWidgets.QComboBox(self.widget)
        self.rateBox.setObjectName("rateBox")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.rateBox.addItem("")
        self.verticalLayout_2.addWidget(self.rateBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clearOutputButton = QtWidgets.QPushButton(self.widget)
        self.clearOutputButton.setObjectName("clearOutputButton")
        self.horizontalLayout_2.addWidget(self.clearOutputButton)
        self.openCloseButton = QtWidgets.QPushButton(self.widget)
        self.openCloseButton.setObjectName("openCloseButton")
        self.horizontalLayout_2.addWidget(self.openCloseButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(mainWindrow)
        self.widget1.setGeometry(QtCore.QRect(20, 413, 551, 171))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.inputEdit = QtWidgets.QTextEdit(self.widget1)
        self.inputEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputEdit.setObjectName("inputEdit")
        self.verticalLayout_4.addWidget(self.inputEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clearInputButton = QtWidgets.QPushButton(self.widget1)
        self.clearInputButton.setObjectName("clearInputButton")
        self.horizontalLayout_3.addWidget(self.clearInputButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.sendButton = QtWidgets.QPushButton(self.widget1)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_3.addWidget(self.sendButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(mainWindrow)
        self.clearInputButton.clicked.connect(self.inputEdit.clear)
        self.clearOutputButton.clicked.connect(self.outputEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(mainWindrow)

    def retranslateUi(self, mainWindrow):
        _translate = QtCore.QCoreApplication.translate
        mainWindrow.setWindowTitle(_translate("mainWindrow", "Form"))
        self.label.setText(_translate("mainWindrow", "端口"))
        self.label_2.setText(_translate("mainWindrow", "波特率"))
        self.portBox.setItemText(0, _translate("mainWindrow", "/dev/ttyUSB0"))
        self.portBox.setItemText(1, _translate("mainWindrow", "/dev/ttyUSB1"))
        self.portBox.setItemText(2, _translate("mainWindrow", "/dev/ttyUSB2"))
        self.portBox.setItemText(3, _translate("mainWindrow", "/dev/ttyUSB3"))
        self.portBox.setItemText(4, _translate("mainWindrow", "/dev/ttyUSB4"))
        self.portBox.setItemText(5, _translate("mainWindrow", "/dev/ttyUSB5"))
        self.rateBox.setItemText(0, _translate("mainWindrow", "1200"))
        self.rateBox.setItemText(1, _translate("mainWindrow", "2400"))
        self.rateBox.setItemText(2, _translate("mainWindrow", "4800"))
        self.rateBox.setItemText(3, _translate("mainWindrow", "9600"))
        self.rateBox.setItemText(4, _translate("mainWindrow", "19200"))
        self.rateBox.setItemText(5, _translate("mainWindrow", "38400"))
        self.rateBox.setItemText(6, _translate("mainWindrow", "57600"))
        self.rateBox.setItemText(7, _translate("mainWindrow", "115200"))
        self.clearOutputButton.setText(_translate("mainWindrow", "清除输出"))
        self.openCloseButton.setText(_translate("mainWindrow", "打开串口"))
        self.clearInputButton.setText(_translate("mainWindrow", "清除输入"))
        self.sendButton.setText(_translate("mainWindrow", "发送"))

